contact_links:
  - name: ðŸ’¬ Misskey official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Misskey
  - name: ðŸ’¬ Start discussion
    url: https://github.com/MisskeyIO/misskey/discussions
    about: The official forum to join conversation and ask question
